services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - timestrolls

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - db
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - timestrolls

  caddy:
    image: caddy:2.6.2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - db
    volumes:
      - ./deployment/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    networks:
      - timestrolls

volumes:
  caddy_data:
  caddy_config:
  postgres:
    driver: local

networks:
  timestrolls:
    name: timestrolls
    driver: bridge
