services:
  # api:
  #   # TODO: remove once https://github.com/rasterio/rasterio-wheels/issues/69 is resolved
  #   # See https://github.com/developmentseed/titiler/discussions/387
  #   platform: linux/amd64
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   container_name: api
  #   command:
  #     [
  #       "uvicorn",
  #       "api.main:app",
  #       "--host",
  #       "0.0.0.0",
  #       "--port",
  #       "8000",
  #       "--workers",
  #       "1",
  #     ]
  #   environment:
  #     # GDAL config
  #     - CPL_TMPDIR=/tmp
  #     - GDAL_CACHEMAX=75%
  #     - GDAL_INGESTED_BYTES_AT_OPEN=32768
  #     - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
  #     - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
  #     - GDAL_HTTP_MULTIPLEX=YES
  #     - GDAL_HTTP_VERSION=2
  #     - PYTHONWARNINGS=ignore
  #     - VSI_CACHE=TRUE
  #     - VSI_CACHE_SIZE=536870912
  #   volumes:
  #     - ./:/tif
  #     - ./resources/tifs:/resources/tifs
  #   restart: unless-stopped
  #   networks:
  #     - timestrolls

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - timestrolls

  caddy:
    image: caddy:2.6.2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - api
    volumes:
      - ./deployment/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    networks:
      - timestrolls

volumes:
  caddy_data:
  caddy_config:

networks:
  timestrolls:
    name: timestrolls
    driver: bridge
