api:
  key: secret

database:
  driver: postgres
  ssl: false
  host: localhost
  port: 5432
  name: timestrolls
  user: user
  password: password

cdn:
  path:
    image: test/timestrolls/images
    podcast: test/timestrolls/podcasts
    tile: test/timestrolls/tiles
  credentials:
    key: ${SPACES_KEY}
    secret: ${SPACES_SECRET}
  bucket: debtray
  endpoint: https://fra1.digitaloceanspaces.com
  #endpoint: /Users/viktor/Work/8gradplus/time-strolls/resources/
#tile:
#  zoom:
#    min: 10
#    max: 11
#size: 256
#format: png
